# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User

def create_super_user(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User.objects.create_superuser('admin', 'admin@mydomain.com', 'demomode')


def create_user(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User.objects.create_user('sunny', 'sunny@mydomain.com', 'demomode')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name="Multiple Choice's text")),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Multiple Choice',
                'verbose_name_plural': 'Multiple Choices',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=256, verbose_name="Question's text")),
                ('marks', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Test name')),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_test.Test'),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplechoice', to='online_test.Question'),
        ),
        migrations.RunPython(create_super_user),
        migrations.RunPython(create_user),
    ]
