# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=256, verbose_name="Question's text"),
        ),
    ]
