# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_auto_20171203_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.AddField(
            model_name='test',
            name='no_of_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Add duration in minutes only'),
        ),
    ]
