# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_auto_20171203_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
